# management.security.enabled=false
# management.endpoints.env.enabled=true
# management.endpoints.web.exposure.include=*

# management:
#   endpoint:
#     env:
#       enabled: true
#     refresh:
#       enabled: true
#   endpoints:
#     web:
#       exposure:
#         include: env
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#Setting the logging levels for the service
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG

server:
  error:
    include-exception: true
